name_max_length: 50
email_max_length: 255
password_min_length: 8
garavatar: 80
size: 30
checkbox: "1"
Post:
  num_post: 5
  size_image: 5
  resize_height: 400
  resize_width: 400
  content_size: 140
  avatar_size: 50
